version: '3.8'

networks:
  backend:

services:
  db:
    image: postgres:11.4-alpine
    container_name: postgres
    networks:
      backend:
        aliases:
          - "database"
    ports:
      - 5430:5432
    volumes:
      - /datastore/pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: interview4jdb
      PGDATA: /var/lib/postgresql/data/pgdata