name: interview4j CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 16.0.1

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: 4.4

      - name: Run unit tests
        run: cd backend/interview4/
        run: mvn test
